-- This is for reference; data is initialized in PersistanceConfig.java

-- insert into developer (name) values ('Moppin');
-- insert into developer (name) values ('Blizzard Entertainment');
-- insert into developer (name) values ('Nintendo EAD');
--
-- insert into publisher (name) values ('Devolver Digital');
-- insert into publisher (name) values ('Blizzard Entertainment');
-- insert into publisher (name) values ('Nintendo');
--
-- insert into genre (name) values ('MMORPG');
-- insert into genre (name) values ('First-Person Shooter');
-- insert into genre (name) values ('Platformer');
-- insert into genre (name) values ('Shoot ''Em Up');